name: smartsense_quest3
description: "A thesis project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # For WebSocket communication
  web_socket_channel: ^3.0.3 # Bumping to latest stable version
  # For handling runtime permissions
  permission_handler: ^12.0.1 # Bumping to latest stable version

  # Critical Fix: Using the newest version of record to resolve internal cross-platform errors
  record: ^6.1.2


  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  frame_sdk: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
  - family: SmartSense # Choose a name for your font family
    fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
  - family: Manrope
    fonts:
        - asset: assets/fonts/Manrope-ExtraBold.otf
        - asset: assets/fonts/Manrope-Regular.otf
        - asset: assets/fonts/Manrope-SemiBold.otf

  assets:
    - assets/icons/linkedin.png
    - assets/icons/icon-park-outline_alignment-left-bottom.png
    - assets/icons/tabler_align-box-center-bottom.png
    - assets/icons/tabler_align-box-center-middle.png
    - assets/icons/tabler_align-box-left-middle.png
    - assets/icons/tabler_align-box-right-bottom.png
    - assets/icons/tabler_align-box-right-middle.png
    - assets/purple-glasses.png
    - assets/white-glasses.png
    - assets/code3.png


